# Generated by Django 4.2 on 2023-05-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
